# Site settings
title: "Hana Kim | Research Professor at BTM KAIST"
description: "Research area: Technology Innovation Management, Decision Making theory, Behavioral economics, Platform economics"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ph.D. Hana Kim"
resume_title:                   "Technology Management, Economics and Policy"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hanakim@kaist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "false"

resume_header_contact_info:     "hanakim@kaist.ac.kr"
display_header_contact_info:    "hanakim@kaist.ac.kr"

resume_header_intro: "<p>Research Professor at KIAST and Senior Researcher at Seoul National University</p>E-mail: hanakim@kaist.ac.kr"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_research_interests: true
resume_section_skills:             true
resume_section_education:          true
resume_section_publications:       true
resume_section_working_papers:     true
resume_section_associations:       true
resume_section_experience:         true
resume_section_links:              true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            ""
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  #resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          ""
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://0620hanakim.github.io"
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default


# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
